"""
engine.py - Per-SIM engine container lifecycle via the Docker SDK.

Each instance runs one `vowifi/engine` container that owns its ePDG tunnel + Asterisk.
The manager renders instance.json, starts/stops/recreates the container with the right
mounts/caps/ports, and reads the engine's runtime status files (bind-mounted run dir):
the swu_ike daemon publishes swu_status.json {state: CONNECTED} for tunnel state.

PC/SC: engine containers are pcscd CLIENTS — they mount the HOST pcscd socket (/run/pcscd).
The pcsc-lite client library in the engine image is pinned to the SAME version as the host
pcscd (Dockerfile PCSC_VERSION == install.sh PCSC_VERSION) so client/server protocol matches.
"""
from __future__ import annotations

import json
import logging
import os
import threading

import docker

from . import config as cfg

log = logging.getLogger("vowifi.engine")

DATA_DIR = cfg.DATA_DIR
IMAGE = os.environ.get("VOWIFI_ENGINE_IMAGE", "vowifi/engine")
PCSCD_SOCK = os.environ.get("VOWIFI_PCSCD_DIR", "/run/pcscd")
# Absolute host path to the project data dir (needed for bind mounts when the manager
# itself runs in a container; defaults to DATA_DIR on the host).
HOST_DATA_DIR = os.environ.get("VOWIFI_HOST_DATA", DATA_DIR)


_client_lock = threading.Lock()
_client_cached: "docker.DockerClient | None" = None


def _client():
    """One shared client. docker.from_env() re-reads the environment, builds a new HTTP
    session over the daemon socket and negotiates an API version on EVERY call — the status
    poller probes each container every few seconds, so paying that repeatedly is a real cost
    on a small board. The SDK is designed to be built once and reused."""
    global _client_cached
    with _client_lock:
        if _client_cached is None:
            _client_cached = docker.from_env()
        return _client_cached


def reset_client():
    """Drop the shared client so the next call rebuilds it (daemon restarted / socket gone)."""
    global _client_cached
    with _client_lock:
        _client_cached = None


def container_name(iid: str) -> str:
    return f"vowifi-engine-{iid}"


def _instance_paths(iid: str):
    base = os.path.join(DATA_DIR, "instances", str(iid))
    host_base = os.path.join(HOST_DATA_DIR, "instances", str(iid))
    os.makedirs(os.path.join(base, "run"), exist_ok=True)
    os.makedirs(os.path.join(base, "logs"), exist_ok=True)
    return base, host_base


def start(inst: dict, settings: dict, dev_mounts: bool = False):
    """(Re)create and start the engine container for an instance."""
    iid = str(inst["id"])
    cfg.write_instance_json(inst, settings)
    base, host_base = _instance_paths(iid)
    ports = inst.get("ports", {})
    client = _client()
    # remove any existing container
    try:
        old = client.containers.get(container_name(iid))
        old.remove(force=True)
    except docker.errors.NotFound:
        pass

    volumes = {
        os.path.join(host_base, "instance.json"): {"bind": "/config/instance.json", "mode": "ro"},
        os.path.join(host_base, "logs"): {"bind": "/logs", "mode": "rw"},
        os.path.join(host_base, "run"): {"bind": "/run/vowifi", "mode": "rw"},
        PCSCD_SOCK: {"bind": "/run/pcscd", "mode": "rw"},
    }
    # TLS cert for the local SIP-TLS / WebRTC (WSS 8089) transport. An explicit cert in
    # settings.tls wins; otherwise fall back to the control plane's own self-signed cert
    # (generated by run.py under $VOWIFI_DATA/certs) so the engine's WSS listener always has
    # a cert — without it Asterisk fails to bind 8089 and the browser softphone can't connect.
    # Bind-mounts must use the HOST path (engine is a sibling container); check existence via
    # the in-container DATA_DIR but mount the HOST_DATA_DIR path.
    tls = settings.get("tls", {})
    cert_host = key_host = None
    if tls.get("cert_path") and os.path.exists(tls["cert_path"]) and \
            tls.get("key_path") and os.path.exists(tls["key_path"]):
        cert_host = os.path.abspath(tls["cert_path"])
        key_host = os.path.abspath(tls["key_path"])
    else:
        # self-signed pair written by run.py: $VOWIFI_DATA/certs/self-signed.{crt,key}
        ss_crt = os.path.join(DATA_DIR, "certs", "self-signed.crt")
        ss_key = os.path.join(DATA_DIR, "certs", "self-signed.key")
        if os.path.exists(ss_crt) and os.path.exists(ss_key):
            cert_host = os.path.join(HOST_DATA_DIR, "certs", "self-signed.crt")
            key_host = os.path.join(HOST_DATA_DIR, "certs", "self-signed.key")
        else:
            log.warning("no TLS cert available for engine %s WSS/8089 — browser softphone will "
                        "not connect until a cert exists (control plane cert at %s missing)", iid, ss_crt)
    if cert_host and key_host:
        volumes[cert_host] = {"bind": "/etc/asterisk/certificate.crt", "mode": "ro"}
        volumes[key_host] = {"bind": "/etc/asterisk/certificate.key", "mode": "ro"}

    if dev_mounts:
        eng = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "engine")
        for f in ["pin_keeper.py", "ami_usim.py", "render.py", "notify.py", "swu_ike.py"]:
            volumes[os.path.join(eng, f)] = {"bind": f"/usr/local/bin/{f}", "mode": "ro"}
        volumes[os.path.join(eng, "entrypoint.sh")] = {"bind": "/entrypoint.sh", "mode": "ro"}
        volumes[os.path.join(eng, "templates")] = {"bind": "/opt/vowifi/templates", "mode": "ro"}

    port_bindings = {
        f"{5060}/udp": ports.get("sip_udp", 5060),
        f"{5061}/tcp": ports.get("sip_tls", 5061),
        f"{8089}/tcp": ports.get("webrtc", 8089),
        f"{5038}/tcp": ports.get("ami", 5038),
    }
    # RTP range
    for p in range(ports.get("rtp_start", 10000), ports.get("rtp_start", 10000) + 60):
        port_bindings[f"{p}/udp"] = p

    c = client.containers.run(
        IMAGE,
        name=container_name(iid),
        detach=True,
        cap_add=["NET_ADMIN"],
        devices=["/dev/net/tun:/dev/net/tun:rwm"],
        volumes=volumes,
        ports=port_bindings,
        restart_policy={"Name": "unless-stopped"},
        environment={"VOWIFI_ID": iid},
        extra_hosts={"host.docker.internal": "host-gateway"},  # so notify.py can reach the manager
    )
    log.info("started engine container %s", c.name)
    return c.id


def stop(iid: str):
    try:
        c = _client().containers.get(container_name(iid))
        c.remove(force=True)
        return True
    except docker.errors.NotFound:
        return False


def is_running(iid: str) -> bool:
    try:
        c = _client().containers.get(container_name(iid))
        return c.status == "running"
    except docker.errors.NotFound:
        return False
    except docker.errors.DockerException:
        reset_client()      # a wedged socket must not be reused by every later probe
        raise


def container_ip(iid: str) -> str | None:
    try:
        c = _client().containers.get(container_name(iid))
        nets = c.attrs["NetworkSettings"]["Networks"]
        for n in nets.values():
            if n.get("IPAddress"):
                return n["IPAddress"]
    except docker.errors.NotFound:
        return None
    except Exception:
        reset_client()
        return None
    return None


def read_run_json(iid: str, name: str) -> dict | None:
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", name)
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def read_pcscf(iid: str) -> str | None:
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", "pcscf")
    try:
        with open(path) as f:
            v = f.read().strip()
            return v or None
    except Exception:
        return None


def tunnel_installed(iid: str) -> bool:
    """True if the ims tunnel is up: the swu_ike daemon writes run/swu_status.json
    {state: CONNECTED} once the SWu (ePDG) IPsec tunnel is established."""
    st = read_run_json(iid, "swu_status.json")
    return st is not None and st.get("state") == "CONNECTED"


def exec_cli(iid: str, command: str) -> str:
    try:
        c = _client().containers.get(container_name(iid))
        rc, out = c.exec_run(["asterisk", "-rx", command])
        return out.decode(errors="replace") if isinstance(out, bytes) else str(out)
    except Exception as e:  # noqa
        return f"error: {e}"


def logs(iid: str, tail: int = 200, since=None) -> str:
    try:
        c = _client().containers.get(container_name(iid))
        kwargs = {"tail": tail}
        if since is not None:
            # docker SDK accepts an int (unix ts) or datetime; used by the SMS delivery
            # watcher to read only the lines emitted after a send.
            kwargs["since"] = since
        return c.logs(**kwargs).decode(errors="replace")
    except Exception as e:  # noqa
        return f"error: {e}"


def charon_log(iid: str, tail: int = 200) -> str:
    """Recent SWu tunnel (IKE) log lines from the instance run dir. The file is named
    charon.log for control-plane/WebUI compatibility (the log-view key is 'charon')."""
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", "charon.log")
    try:
        with open(path, errors="replace") as f:
            return "".join(f.readlines()[-tail:])
    except Exception:
        return ""


def usim_status(iid: str) -> dict:
    return read_run_json(iid, "usim_status.json") or {}

