"""
engine.py - Per-SIM engine container lifecycle via the Docker SDK.

Each instance runs one `vowifi/engine` container that owns its ePDG tunnel + Asterisk.
The manager renders instance.json, starts/stops/recreates the container with the right
mounts/caps/ports, and reads the engine's runtime status files (bind-mounted run dir):
the swu_ike daemon publishes swu_status.json {state: CONNECTED} for tunnel state.

PC/SC: engine containers are pcscd CLIENTS — they mount the HOST pcscd socket (/run/pcscd).
The pcsc-lite client library in the engine image is pinned to the SAME version as the host
pcscd (Dockerfile PCSC_VERSION == install.sh PCSC_VERSION) so client/server protocol matches.
"""
from __future__ import annotations

import json
import logging
import os

import docker

from . import config as cfg

log = logging.getLogger("vowifi.engine")

DATA_DIR = cfg.DATA_DIR
IMAGE = os.environ.get("VOWIFI_ENGINE_IMAGE", "vowifi/engine")
PCSCD_SOCK = os.environ.get("VOWIFI_PCSCD_DIR", "/run/pcscd")
# Absolute host path to the project data dir (needed for bind mounts when the manager
# itself runs in a container; defaults to DATA_DIR on the host).
HOST_DATA_DIR = os.environ.get("VOWIFI_HOST_DATA", DATA_DIR)


def _client():
    return docker.from_env()


def container_name(iid: str) -> str:
    return f"vowifi-engine-{iid}"


def _instance_paths(iid: str):
    base = os.path.join(DATA_DIR, "instances", str(iid))
    host_base = os.path.join(HOST_DATA_DIR, "instances", str(iid))
    os.makedirs(os.path.join(base, "run"), exist_ok=True)
    os.makedirs(os.path.join(base, "logs"), exist_ok=True)
    return base, host_base


def start(inst: dict, settings: dict, dev_mounts: bool = False):
    """(Re)create and start the engine container for an instance."""
    iid = str(inst["id"])
    cfg.write_instance_json(inst, settings)
    base, host_base = _instance_paths(iid)
    ports = inst.get("ports", {})
    client = _client()
    # remove any existing container
    try:
        old = client.containers.get(container_name(iid))
        old.remove(force=True)
    except docker.errors.NotFound:
        pass

    volumes = {
        os.path.join(host_base, "instance.json"): {"bind": "/config/instance.json", "mode": "ro"},
        os.path.join(host_base, "logs"): {"bind": "/logs", "mode": "rw"},
        os.path.join(host_base, "run"): {"bind": "/run/vowifi", "mode": "rw"},
        PCSCD_SOCK: {"bind": "/run/pcscd", "mode": "rw"},
    }
    # TLS cert for the local SIP-TLS / WebRTC (WSS 8089) transport. An explicit cert in
    # settings.tls wins; otherwise fall back to the control plane's own self-signed cert
    # (generated by run.py under $VOWIFI_DATA/certs) so the engine's WSS listener always has
    # a cert — without it Asterisk fails to bind 8089 and the browser softphone can't connect.
    # Bind-mounts must use the HOST path (engine is a sibling container); check existence via
    # the in-container DATA_DIR but mount the HOST_DATA_DIR path.
    tls = settings.get("tls", {})
    cert_host = key_host = None
    if tls.get("cert_path") and os.path.exists(tls["cert_path"]) and \
            tls.get("key_path") and os.path.exists(tls["key_path"]):
        cert_host = os.path.abspath(tls["cert_path"])
        key_host = os.path.abspath(tls["key_path"])
    else:
        # self-signed pair written by run.py: $VOWIFI_DATA/certs/self-signed.{crt,key}
        ss_crt = os.path.join(DATA_DIR, "certs", "self-signed.crt")
        ss_key = os.path.join(DATA_DIR, "certs", "self-signed.key")
        if os.path.exists(ss_crt) and os.path.exists(ss_key):
            cert_host = os.path.join(HOST_DATA_DIR, "certs", "self-signed.crt")
            key_host = os.path.join(HOST_DATA_DIR, "certs", "self-signed.key")
        else:
            log.warning("no TLS cert available for engine %s WSS/8089 — browser softphone will "
                        "not connect until a cert exists (control plane cert at %s missing)", iid, ss_crt)
    if cert_host and key_host:
        volumes[cert_host] = {"bind": "/etc/asterisk/certificate.crt", "mode": "ro"}
        volumes[key_host] = {"bind": "/etc/asterisk/certificate.key", "mode": "ro"}

    eng = _engine_tree()
    # Always overlay notify.py when the host tree has it. Inbound SMS / call history POST
    # to /api/engine/event with X-Vowifi-Engine-Token; an older engine image without that
    # header silently 401s after Web-auth upgrades. Binding the repo copy avoids requiring
    # an immediate `docker build` of vowifi/engine just to restore receive path.
    notify_src = notify_script_path()
    if notify_src:
        volumes[notify_src] = {"bind": "/usr/local/bin/notify.py", "mode": "ro"}

    if dev_mounts:
        for f in ["pin_keeper.py", "ami_usim.py", "render.py", "notify.py", "swu_ike.py"]:
            src = os.path.join(eng, f)
            if os.path.isfile(src):
                volumes[src] = {"bind": f"/usr/local/bin/{f}", "mode": "ro"}
        ep = os.path.join(eng, "entrypoint.sh")
        if os.path.isfile(ep):
            volumes[ep] = {"bind": "/entrypoint.sh", "mode": "ro"}
        tpl = os.path.join(eng, "templates")
        if os.path.isdir(tpl):
            volumes[tpl] = {"bind": "/opt/vowifi/templates", "mode": "ro"}

    port_bindings = {
        f"{5060}/udp": ports.get("sip_udp", 5060),
        f"{5061}/tcp": ports.get("sip_tls", 5061),
        f"{8089}/tcp": ports.get("webrtc", 8089),
        f"{5038}/tcp": ports.get("ami", 5038),
    }
    # RTP range
    for p in range(ports.get("rtp_start", 10000), ports.get("rtp_start", 10000) + 60):
        port_bindings[f"{p}/udp"] = p

    c = client.containers.run(
        IMAGE,
        name=container_name(iid),
        detach=True,
        cap_add=["NET_ADMIN"],
        devices=["/dev/net/tun:/dev/net/tun:rwm"],
        volumes=volumes,
        ports=port_bindings,
        restart_policy={"Name": "unless-stopped"},
        environment={"VOWIFI_ID": iid},
        extra_hosts={"host.docker.internal": "host-gateway"},  # so notify.py can reach the manager
    )
    log.info("started engine container %s", c.name)
    # render.py writes ENGINE_TOKEN into the bind-mounted run dir; also patch from the
    # control plane so a race / older render still leaves a usable callback secret.
    try:
        cfg.sync_engine_token_to_run_dirs()
    except Exception as e:  # noqa
        log.debug("post-start engine token sync: %r", e)
    return c.id


def stop(iid: str):
    try:
        c = _client().containers.get(container_name(iid))
        c.remove(force=True)
        return True
    except docker.errors.NotFound:
        return False


def is_running(iid: str) -> bool:
    try:
        c = _client().containers.get(container_name(iid))
        return c.status == "running"
    except docker.errors.NotFound:
        return False


def container_ips(iid: str) -> list[str]:
    """All IPv4/IPv6 addresses attached to the engine container (every docker network)."""
    try:
        c = _client().containers.get(container_name(iid))
        nets = ((c.attrs.get("NetworkSettings") or {}).get("Networks") or {})
        ips: list[str] = []
        for n in nets.values():
            for key in ("IPAddress", "GlobalIPv6Address"):
                addr = (n.get(key) or "").strip()
                if addr and addr not in ips:
                    ips.append(addr)
        return ips
    except Exception:
        return []


def container_ip(iid: str) -> str | None:
    ips = container_ips(iid)
    return ips[0] if ips else None


def _engine_tree() -> str:
    return os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "engine")


def notify_script_path() -> str | None:
    path = os.path.join(_engine_tree(), "notify.py")
    return path if os.path.isfile(path) else None


def push_notify_script_to_running() -> int:
    """Hot-patch /usr/local/bin/notify.py inside every running engine container.

    Auth upgrades require notify.py to send X-Vowifi-Engine-Token. Waiting for the
    next Stop→Start leaves inbound SMS/calls broken; docker put_archive fixes live
    containers without tearing down the IPsec/IMS session.
    """
    import io
    import tarfile

    src = notify_script_path()
    if not src:
        return 0
    try:
        data = open(src, "rb").read()
    except OSError as e:
        log.warning("cannot read notify.py for hot-patch: %r", e)
        return 0
    client = _client()
    updated = 0
    for inst in cfg.list_instances():
        iid = str(inst["id"])
        try:
            c = client.containers.get(container_name(iid))
            if c.status != "running":
                continue
            buf = io.BytesIO()
            with tarfile.open(fileobj=buf, mode="w") as tar:
                info = tarfile.TarInfo(name="notify.py")
                info.size = len(data)
                info.mode = 0o755
                tar.addfile(info, io.BytesIO(data))
            buf.seek(0)
            if not c.put_archive("/usr/local/bin", buf):
                log.warning("put_archive notify.py failed for engine %s", iid)
                continue
            updated += 1
        except docker.errors.NotFound:
            continue
        except Exception as e:  # noqa
            log.warning("hot-patch notify.py on engine %s failed: %r", iid, e)
    return updated


def heal_callback_auth() -> dict:
    """Repair engine→control callback auth for already-running lines.

    1) Write ENGINE_TOKEN into each host-mounted engine.env (notify re-reads per call).
    2) Push the current notify.py into running containers (adds the token header).
    """
    token_files = 0
    try:
        token_files = cfg.sync_engine_token_to_run_dirs()
    except Exception as e:  # noqa
        log.warning("sync_engine_token_to_run_dirs failed: %r", e)
    notify_pushed = 0
    try:
        notify_pushed = push_notify_script_to_running()
    except Exception as e:  # noqa
        log.warning("push_notify_script_to_running failed: %r", e)
    return {"token_files_updated": token_files, "notify_pushed": notify_pushed}


def callback_health() -> dict:
    """Snapshot used by GET /api/system/engine-callbacks (authenticated)."""
    token = cfg.engine_callback_token()
    rows = []
    for inst in cfg.list_instances():
        iid = str(inst["id"])
        env_path = os.path.join(DATA_DIR, "instances", iid, "run", "engine.env")
        env_token = ""
        if os.path.isfile(env_path):
            try:
                with open(env_path, encoding="utf-8") as f:
                    for line in f:
                        if line.startswith("ENGINE_TOKEN="):
                            env_token = line.split("=", 1)[1].strip()
                            break
            except OSError:
                pass
        running = is_running(iid)
        rows.append({
            "id": iid,
            "running": running,
            "container_ips": container_ips(iid) if running else [],
            "engine_env_has_token": bool(env_token),
            "engine_env_token_matches": bool(env_token and token and env_token == token),
        })
    return {
        "engine_token_configured": bool(token),
        "notify_script_on_host": bool(notify_script_path()),
        "callback_path": "/api/engine/event",
        "events_via_callback": [
            "sms_in", "sms_out",
            "call_in", "call_out", "call_result",
            "tunnel_up", "tunnel_down", "pcscf",
            "registered", "unregistered", "cp_mode_resolved",
        ],
        "apis_not_via_callback": [
            "POST /api/instances/{id}/sms/send",
            "POST /api/instances/{id}/call",
            "POST /api/instances/{id}/hangup",
            "POST /api/instances/{id}/register",
            "GET  /api/instances/{id}/status (AMI + run files)",
            "GET  /api/instances/{id}/logs",
            "eSIM / PIN / provision / start / stop",
        ],
        "instances": rows,
    }


def read_run_json(iid: str, name: str) -> dict | None:
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", name)
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def read_pcscf(iid: str) -> str | None:
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", "pcscf")
    try:
        with open(path) as f:
            v = f.read().strip()
            return v or None
    except Exception:
        return None


def tunnel_installed(iid: str) -> bool:
    """True if the ims tunnel is up: the swu_ike daemon writes run/swu_status.json
    {state: CONNECTED} once the SWu (ePDG) IPsec tunnel is established."""
    st = read_run_json(iid, "swu_status.json")
    return st is not None and st.get("state") == "CONNECTED"


def exec_cli(iid: str, command: str) -> str:
    try:
        c = _client().containers.get(container_name(iid))
        rc, out = c.exec_run(["asterisk", "-rx", command])
        return out.decode(errors="replace") if isinstance(out, bytes) else str(out)
    except Exception as e:  # noqa
        return f"error: {e}"


def logs(iid: str, tail: int = 200, since=None) -> str:
    try:
        c = _client().containers.get(container_name(iid))
        kwargs = {"tail": tail}
        if since is not None:
            # docker SDK accepts an int (unix ts) or datetime; used by the SMS delivery
            # watcher to read only the lines emitted after a send.
            kwargs["since"] = since
        return c.logs(**kwargs).decode(errors="replace")
    except Exception as e:  # noqa
        return f"error: {e}"


def charon_log(iid: str, tail: int = 200) -> str:
    """Recent SWu tunnel (IKE) log lines from the instance run dir. The file is named
    charon.log for control-plane/WebUI compatibility (the log-view key is 'charon')."""
    path = os.path.join(DATA_DIR, "instances", str(iid), "run", "charon.log")
    try:
        with open(path, errors="replace") as f:
            return "".join(f.readlines()[-tail:])
    except Exception:
        return ""


def usim_status(iid: str) -> dict:
    return read_run_json(iid, "usim_status.json") or {}

